# Site settings
title: "cybertus"
bye_message: "Thx!"
baseurl: ""
url: "https://cybertus.github.io"
disqus: Cybertus

# Header settings
nick: "Cybertus"
mail:
    domain: "protonmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "Cybertus"
blog:
    server: "wordpress.com"
    nick: "Cybertus"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
