# Site settings
title: "Cybertus"
bye_message: "Thx!"
baseurl: ""
url: "https://cybertus.github.io"
disqus: cybertus

# Header settings
nick: "[\"cybertus\", \"thecybertus\", \"alrubal\"]"
twitter:
    server: "twitter.com"
    nick: "TheCybertus"
source_code:
    server: "github.com"
    nick: "cybertus"
linkedin:
    server: "linkedin.com/in"
    nick: "alrubal"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/